FROM rickalm/dcos:1.7_base_dind

VOLUME [ "/var/lib/rexray" ]

ADD target_aws_common/setup/bootstrap_aws.sh /
RUN bash /bootstrap_aws.sh && rm /bootstrap_aws.sh

RUN \
  \
  # Install ext filesystem tools; \
  \
  yum -y install e2fsprogs.x86_64 \
    || exit 1; \
  \
  yum -y clean all \
    || exit 1; \
  \
  # Install Rexray; \
  \
  curl -sSL https://dl.bintray.com/emccode/rexray/install | sh - \
    || exit 1; \
  \
  /bin/true
