##################################
###
### This project starts from centos:7 build and installs systemd (container) and latest docker
###
### - remount /sys/fs/cgroups within the context its launched into (side effect of --priv)
### - launches docker (Working how to let SystemD do this
### - passes control to SystemD (unless told to do otherwise)
###
### Ideas (and portions of code in the project) originated from
###  https://github.com/jpetazzo/dind
###  https://github.com/maci0/docker-systemd-unpriv
###
##################################

FROM rickalm/centos7-base:7
MAINTAINER Rick Alm "rickalm@aol.com"

# Install all of the external components as a single step to reduce layer size
#
RUN \
  \
  # Launch Docker through start script; \
  \
  systemctl enable \
    docker.service \
    docker.socket \
    || exit 1; \
  \
  /bin/true

ENTRYPOINT  ["/start_systemd.sh"]

# Add our start scripts to the image
#
ADD files /
